### ISSUE TITLE
some bug in executemany

### ISSUE THREAD

**Issue by ewing333** [hongqn/umysqldb#7]
import umysqldb
sql = 'INSERT INTO _test(id,val) VALUES(%s,%s) ON DUPLICATE KEY UPDATE id=VALUES(id),val=VALUES(val)'
args = [(44495, 1),(44495, 2)]

conn = umysqldb.connect(  host='127.0.0.1',
                              user='root',
                              passwd='',
                              db='test',
                              port=3306 )
cursor = conn.cursor( umysqldb.cursors.DictCursor )
cursor.executemany(sql,args)

Traceback (most recent call last):
  File "Y:\trunk\TestLizr.py", line 43, in <module>
    cursor.executemany(sql,args)
  File "C:\Python27\lib\site-packages\umysqldb\cursors.py", line 59, in executemany
    return self.execute(multirow_query, _flatten(args))
  File "C:\Python27\lib\site-packages\umysqldb\cursors.py", line 77, in execute
    result = super(DictCursor, self).execute(query, args)
  File "C:\Python27\lib\site-packages\umysqldb\cursors.py", line 33, in execute
    self.errorhandler(self, exc, value)
  File "C:\Python27\lib\site-packages\umysqldb\connections.py", line 43, in defaulterrorhandler
    raise errorclass, errorvalue
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(val)' at line 1")
## -- 表的结构 `_test`

CREATE TABLE IF NOT EXISTS `_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `val` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COMMENT='测试表';
'''

**Comment by hongqn** [comment]
MySQLdb raises exception on this test case, too, although it raises a different type of exception.

```
mysql> CREATE TABLE IF NOT EXISTS _test (
    -> id int(11) NOT NULL AUTO_INCREMENT,
    -> val varchar(50) NOT NULL,
    -> PRIMARY KEY (id)
    -> ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='测试表';
Query OK, 0 rows affected (0.02 sec)
```

```
>>> import MySQLdb
>>> sql = 'INSERT INTO _test(id,val) VALUES(%s,%s) ON DUPLICATE KEY UPDATE GoodsType=VALUES(GoodsType),GoodsId=VALUES(GoodsId),GoodsNum=VALUES(GoodsNum),CreateTime=VALUES(CreateTime)'
>>> args = [(44495, 1),(44495, 2)]
>>> conn = MySQLdb.connect(db='test')
>>> cursor = conn.cursor(MySQLdb.cursors.DictCursor)
>>> cursor.executemany(sql,args)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hongqn/Envs/tmp/lib/python2.7/site-packages/MySQLdb/cursors.py", line 206, in executemany
    r = r + self.execute(query, a)
  File "/Users/hongqn/Envs/tmp/lib/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/Users/hongqn/Envs/tmp/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1054, "Unknown column 'GoodsType' in 'field list'")
```

**Comment by ewing333** [comment]
哦不对 sql那里改漏了 看更新后的issue

------------------ 原始邮件 ------------------
发件人: "Qiangning Hong";notifications@github.com;
发送时间: 2013年12月6日(星期五) 下午2:24
收件人: "hongqn/umysqldb"umysqldb@noreply.github.com; 
抄送: "Ewing??"ewing333@qq.com; 
主题: Re: [umysqldb] some bug in executemany (#7)

MySQLdb raises exception on this test case, too, although it raises a different type of exception.
 mysql> CREATE TABLE IF NOT EXISTS _test (     -> id int(11) NOT NULL AUTO_INCREMENT,     -> val varchar(50) NOT NULL,     -> PRIMARY KEY (id)     -> ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='测试表'; Query OK, 0 rows affected (0.02 sec)  >>> import MySQLdb >>> sql = 'INSERT INTO _test(id,val) VALUES(%s,%s) ON DUPLICATE KEY UPDATE GoodsType=VALUES(GoodsType),GoodsId=VALUES(GoodsId),GoodsNum=VALUES(GoodsNum),CreateTime=VALUES(CreateTime)' >>> args = [(44495, 1),(44495, 2)] >>> conn = MySQLdb.connect(db='test') >>> cursor = conn.cursor(MySQLdb.cursors.DictCursor) >>> cursor.executemany(sql,args) Traceback (most recent call last):   File "<stdin>", line 1, in <module>   File "/Users/hongqn/Envs/tmp/lib/python2.7/site-packages/MySQLdb/cursors.py", line 206, in executemany     r = r + self.execute(query, a)   File "/Users/hongqn/Envs/tmp/lib/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute     self.errorhandler(self, exc, value)   File "/Users/hongqn/Envs/tmp/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler     raise errorclass, errorvalue _mysql_exceptions.OperationalError: (1054, "Unknown column 'GoodsType' in 'field list'")
