### ISSUE TITLE
MySQLdb.converters not supported - not compatible with Django 1.6 

### ISSUE THREAD

**Issue by TTimo** [hongqn/umysqldb#8]
In Django 1.6 (and I believe since at least 1.5), the mysql backend imports the following:

from MySQLdb.converters import conversions, Thing2Literal

Those seem to be utility functions - I am not sure how best to approach this. Advice?

**Comment by hongqn** [comment]
Could you do me a favor to test if pymysql-0.6.1 compatible with Django 1.6?  If yes, I'll try to integrate with latest pymysql.

Currently only pymysql<0.6 supported (see #4), which has no pymysql.converters.Thing2Literal defined.

**Comment by TTimo** [comment]
Yes, it is .. I was running latest PyMySQL earlier today. Unfortunately in my load tests PyMySQL has just about the same performance as the builtin Django driver. It seems the gain of gevent is cancelled out by a 'pure python' driver. That's how I ended up trying umysql..

**Comment by hongqn** [comment]
Feel free to reopen this issue if the newest version still fails.

**Comment by TTimo** [comment]
Latest works great, thank you so much for fixing this.

FYI - in my very simple load testing, performance is roughly 20% better than the default, non-gevent driver in Django. PyMySQL is barely any better than the non-gevent version.

**Comment by TTimo** [comment]
I spoke too soon. The very simple code paths I was using in my tests are fine with latest, but it doesn't actual pass unit tests.

PyMySQL passes the builtin tests and my own app's unit tests fine. But the latest umysqldb does this:

https://gist.github.com/TTimo/8584200

I also saw the following when doing manual calls:

  File "/opt/viduo/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 62, in parse_datetime_with_timezone_supp
ort
    dt = parse_datetime(value)
  File "/opt/viduo/local/lib/python2.7/site-packages/pymysql/converters.py", line 116, in convert_datetime
    if ' ' in obj:
TypeError: argument of type 'datetime.datetime' is not iterable
